<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Телеком" data-toc-modified-id="Телеком-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Телеком</a></span><ul class="toc-item"><li><span><a href="#План-работы" data-toc-modified-id="План-работы-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>План работы</a></span></li><li><span><a href="#Предобработка" data-toc-modified-id="Предобработка-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Предобработка</a></span></li><li><span><a href="#Исследовательский-анализ-данных" data-toc-modified-id="Исследовательский-анализ-данных-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Исследовательский анализ данных</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Построение-модели" data-toc-modified-id="Построение-модели-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Построение модели</a></span><ul class="toc-item"><li><span><a href="#CatBoost" data-toc-modified-id="CatBoost-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>CatBoost</a></span></li></ul></li><li><span><a href="#Отчёт" data-toc-modified-id="Отчёт-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Отчёт</a></span></li></ul></li></ul></div>

# Телеком

## План работы
* Предобработка данных: ознакомиться с данными, объединить датасеты, обработать пропуски, дубликаты и некорректные значения, привести данные к корректным типам, выделить целевой признак, удалить лишние столбцы.
* Исследовательский анализ данных: исследовать категориальные и количественные признаки, баланс классов целевого признака.
* Построение модели: подготовить признаки к обучению, разделить датасет на выборки, обучить модель с различными гиперпараметрами и выбрать финальную модель с параметрами AUC-ROC ≥ 0.88.
* Тестирование модели: проверить качество финальной модели на тестовой выборке.
* Вывод: проанализировать полученные результаты.

In [90]:
!pip install sweetviz -q

In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings as warn
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import roc_auc_score, accuracy_score, recall_score, precision_score, roc_curve
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle
from imblearn.over_sampling import BorderlineSMOTE
import sweetviz as sv
from catboost import cv, Pool

##  Предобработка

**Загрузим данные**

In [92]:
path_local = '/Users/bogda/anaconda3/projects/praktikum/project_project/final_provider/'
path_yandex = '/datasets/final_provider/'

In [93]:
files = ['contract', 'personal', 'internet', 'phone']
data = {}

In [94]:
def tryexept(path):
    for i in files:
        data[i] = pd.read_csv(path + i + '.csv', index_col= 'customerID')
        print('\n' + i)
        display(data[i].sample(5))
        data[i].info()
        print('—' * 54)

In [95]:
try:
    tryexept(path_local)
except FileNotFoundError as e:
    print(e)
    tryexept(path_yandex)

contract

,BeginDate,EndDate,Type,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
customerID,,,,,,,
4716-MRVEN,2017-09-01,No,One year,No,Mailed check,20.00,599.3
3675-YDUPJ,2019-04-01,No,Month-to-month,Yes,Mailed check,19.85,193.05
1891-QRQSA,2014-10-01,No,Two year,Yes,Bank transfer (automatic),111.60,7099
5515-IDEJJ,2019-12-01,2020-01-01 00:00:00,Month-to-month,No,Mailed check,19.90,19.9
5143-EGQFK,2019-01-01,2019-11-01 00:00:00,Month-to-month,Yes,Electronic check,29.65,291.4

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   BeginDate         7043 non-null   object
 1   EndDate           7043 non-null   object
 2   Type              7043 non-null   object
 3   PaperlessBilling  7043 non-null   object
 4   PaymentMethod     7043 non-null   object
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7043 non-null   object
dtypes: float64(1), object(6)
memory usage: 440.2+ KB
——————————————————————————————————————————————————————

personal

            gender  SeniorCitizen Partner Dependents
customerID
7841-TZDMQ    Male              0      No         No
6629-CZTTH    Male              0      No         No
9932-WBWIK    Male              0      No         No
3251-YMVWZ    Male              0      No         No
7716-YTYHG  Female              0     Yes        Yes

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         7043 non-null   object
 1   SeniorCitizen  7043 non-null   int64
 2   Partner        7043 non-null   object
 3   Dependents     7043 non-null   object
dtypes: int64(1), object(3)
memory usage: 275.1+ KB
——————————————————————————————————————————————————————

internet

,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
customerID,,,,,,,
3179-GBRWV,DSL,Yes,Yes,No,No,No,Yes
1703-MGIAB,DSL,No,No,Yes,Yes,Yes,No
2144-ESWKO,DSL,Yes,No,Yes,No,No,No
6339-YPSAH,Fiber optic,No,No,Yes,No,No,No
7641-TQFHN,Fiber optic,No,No,No,Yes,Yes,Yes

<class 'pandas.core.frame.DataFrame'>
Index: 5517 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   InternetService   5517 non-null   object
 1   OnlineSecurity    5517 non-null   object
 2   OnlineBackup      5517 non-null   object
 3   DeviceProtection  5517 non-null   object
 4   TechSupport       5517 non-null   object
 5   StreamingTV       5517 non-null   object
 6   StreamingMovies   5517 non-null   object
dtypes: object(7)
memory usage: 344.8+ KB
——————————————————————————————————————————————————————

phone

           MultipleLines
customerID
2990-HWIML            No
8562-GHPPI            No
6270-OMFIW            No
8417-FMLZI            No
4919-MOAVT            No

<class 'pandas.core.frame.DataFrame'>
Index: 6361 entries, 5575-GNVDE to 3186-AJIEK
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MultipleLines  6361 non-null   object
dtypes: object(1)
memory usage: 99.4+ KB
——————————————————————————————————————————————————————

**Небольшой обзор, пропусков нет(на первый взгляд:), две последних таблицы содержат меньше данных чем первые, причина в том что клиенты могут пользоваться разными услугами независимо - заполнить пропуски. Не соответсвтие типов данных и столбцов в таблице contract 'BeginDate', 'EndDate' - привести к дате, 'TotalCharges' к float.В таблице personal столбец 'SeniorSitizen' числовой хотя это категоральный признак. Разный регистр, нет целевого признака.**

**Объеденим таблицы в один датасет, приведем названия столбцов к одному регистру**

In [96]:
df = data['contract'].join(data['personal']).join(data['internet']).join(data['phone'])
df.columns = [k.lower() for k in list(df.columns)]
display(df.sample(5))
df.info()

,begindate,enddate,type,paperlessbilling,paymentmethod,monthlycharges,totalcharges,gender,seniorcitizen,partner,dependents,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,multiplelines
customerID,,,,,,,,,,,,,,,,,,,
0568-ONFPC,2019-07-01,2019-12-01 00:00:00,Month-to-month,Yes,Bank transfer (automatic),25.90,135,Male,0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
3452-ABWRL,2016-03-01,No,Month-to-month,Yes,Credit card (automatic),86.05,3865.6,Male,1,No,No,Fiber optic,No,No,No,No,Yes,No,Yes
0722-TROQR,2019-08-01,2019-12-01 00:00:00,Month-to-month,Yes,Electronic check,74.90,321.75,Female,1,No,No,Fiber optic,No,No,No,No,No,No,Yes
4424-TKOPW,2019-10-01,2019-12-01 00:00:00,Month-to-month,Yes,Electronic check,93.85,196.75,Male,1,No,No,Fiber optic,No,No,No,No,Yes,Yes,Yes
7599-FKVXZ,2016-05-01,2019-11-01 00:00:00,Month-to-month,Yes,Bank transfer (automatic),106.15,4512.7,Male,0,Yes,No,Fiber optic,No,No,Yes,Yes,Yes,Yes,Yes

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   begindate         7043 non-null   object
 1   enddate           7043 non-null   object
 2   type              7043 non-null   object
 3   paperlessbilling  7043 non-null   object
 4   paymentmethod     7043 non-null   object
 5   monthlycharges    7043 non-null   float64
 6   totalcharges      7043 non-null   object
 7   gender            7043 non-null   object
 8   seniorcitizen     7043 non-null   int64
 9   partner           7043 non-null   object
 10  dependents        7043 non-null   object
 11  internetservice   5517 non-null   object
 12  onlinesecurity    5517 non-null   object
 13  onlinebackup      5517 non-null   object
 14  deviceprotection  5517 non-null   object
 15  techsupport       5517 non-null   object
 16  streamingtv       5517 non-null   object
 17  streamingmovies   5517 non-null   object
 18  multiplelines     6361 non-null   object
dtypes: float64(1), int64(1), object(17)
memory usage: 1.3+ MB

**Создадим столбец 'outflow' с целевым признаком**

In [97]:
def func(row):
    if row.enddate == "No":
        return 0
    else:
        return 1
df['outflow'] = df.apply(func, axis=1)

In [98]:
df

,begindate,enddate,type,paperlessbilling,paymentmethod,monthlycharges,totalcharges,gender,seniorcitizen,partner,dependents,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,multiplelines,outflow
customerID,,,,,,,,,,,,,,,,,,,,
7590-VHVEG,2020-01-01,No,Month-to-month,Yes,Electronic check,29.85,29.85,Female,0,Yes,No,DSL,No,Yes,No,No,No,No,NaN,0
5575-GNVDE,2017-04-01,No,One year,No,Mailed check,56.95,1889.5,Male,0,No,No,DSL,Yes,No,Yes,No,No,No,No,0
3668-QPYBK,2019-10-01,2019-12-01 00:00:00,Month-to-month,Yes,Mailed check,53.85,108.15,Male,0,No,No,DSL,Yes,Yes,No,No,No,No,No,1
7795-CFOCW,2016-05-01,No,One year,No,Bank transfer (automatic),42.30,1840.75,Male,0,No,No,DSL,Yes,No,Yes,Yes,No,No,NaN,0
9237-HQITU,2019-09-01,2019-11-01 00:00:00,Month-to-month,Yes,Electronic check,70.70,151.65,Female,0,No,No,Fiber optic,No,No,No,No,No,No,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6840-RESVB,2018-02-01,No,One year,Yes,Mailed check,84.80,1990.5,Male,0,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Yes,0
2234-XADUH,2014-02-01,No,One year,Yes,Credit card (automatic),103.20,7362.9,Female,0,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Yes,0
4801-JZAZL,2019-03-01,No,Month-to-month,Yes,Electronic check,29.60,346.45,Female,0,Yes,Yes,DSL,Yes,No,No,No,No,No,NaN,0
8361-LTMKD,2019-07-01,2019-11-01 00:00:00,Month-to-month,Yes,Mailed check,74.40,306.6,Male,1,Yes,No,Fiber optic,No,No,No,No,No,No,Yes,1
3186-AJIEK,2014-08-01,No,Two year,Yes,Bank transfer (automatic),105.65,6844.5,Male,0,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,No,0

**Заменим столбцы 'begindate', 'enddate' на столбец 'contract_length' так мы избавимся от утечки целевого признака и сохраним информативность временного признака. Для начала приведём их к дате и заменим пропуски на дату предоставления данных**

In [99]:
df['begindate'] = pd.to_datetime(df['begindate'], errors='coerce')
df['enddate'] = pd.to_datetime(df['enddate'], errors='coerce')

In [100]:
df['enddate'].fillna(pd.to_datetime('2020-02-01'), inplace=True)

In [101]:
def duration(row):
    return len(pd.date_range(start=row['begindate'], end=row['enddate']))
df['contract_length'] = df.apply(duration, axis=1)
df.drop(['begindate', 'enddate'], axis=1, inplace=True)

In [102]:
df

,type,paperlessbilling,paymentmethod,monthlycharges,totalcharges,gender,seniorcitizen,partner,dependents,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,multiplelines,outflow,contract_length
customerID,,,,,,,,,,,,,,,,,,,
7590-VHVEG,Month-to-month,Yes,Electronic check,29.85,29.85,Female,0,Yes,No,DSL,No,Yes,No,No,No,No,NaN,0,32
5575-GNVDE,One year,No,Mailed check,56.95,1889.5,Male,0,No,No,DSL,Yes,No,Yes,No,No,No,No,0,1037
3668-QPYBK,Month-to-month,Yes,Mailed check,53.85,108.15,Male,0,No,No,DSL,Yes,Yes,No,No,No,No,No,1,62
7795-CFOCW,One year,No,Bank transfer (automatic),42.30,1840.75,Male,0,No,No,DSL,Yes,No,Yes,Yes,No,No,NaN,0,1372
9237-HQITU,Month-to-month,Yes,Electronic check,70.70,151.65,Female,0,No,No,Fiber optic,No,No,No,No,No,No,No,1,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6840-RESVB,One year,Yes,Mailed check,84.80,1990.5,Male,0,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Yes,0,731
2234-XADUH,One year,Yes,Credit card (automatic),103.20,7362.9,Female,0,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Yes,0,2192
4801-JZAZL,Month-to-month,Yes,Electronic check,29.60,346.45,Female,0,Yes,Yes,DSL,Yes,No,No,No,No,No,NaN,0,338
8361-LTMKD,Month-to-month,Yes,Mailed check,74.40,306.6,Male,1,Yes,No,Fiber optic,No,No,No,No,No,No,Yes,1,124
3186-AJIEK,Two year,Yes,Bank transfer (automatic),105.65,6844.5,Male,0,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,No,0,2011

**Приведём данные столбца totalcharges к вещественному типу.**

In [103]:
df['totalcharges'] = pd.to_numeric(df['totalcharges'], errors='coerce')

**Изучим пропуски**

In [104]:
df[df['totalcharges'].isna()]

,type,paperlessbilling,paymentmethod,monthlycharges,totalcharges,gender,seniorcitizen,partner,dependents,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,multiplelines,outflow,contract_length
customerID,,,,,,,,,,,,,,,,,,,
4472-LVYGI,Two year,Yes,Bank transfer (automatic),52.55,NaN,Female,0,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,No,NaN,0,1
3115-CZMZD,Two year,No,Mailed check,20.25,NaN,Male,0,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,0,1
5709-LVOEQ,Two year,No,Mailed check,80.85,NaN,Female,0,Yes,Yes,DSL,Yes,Yes,Yes,No,Yes,Yes,No,0,1
4367-NUYAO,Two year,No,Mailed check,25.75,NaN,Male,0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,0,1
1371-DWPAZ,Two year,No,Credit card (automatic),56.05,NaN,Female,0,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,No,NaN,0,1
7644-OMVMY,Two year,No,Mailed check,19.85,NaN,Male,0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,0,1
3213-VVOLG,Two year,No,Mailed check,25.35,NaN,Male,0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,0,1
2520-SGTTA,Two year,No,Mailed check,20.00,NaN,Female,0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,0,1
2923-ARZLG,One year,Yes,Mailed check,19.70,NaN,Male,0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,0,1
4075-WKNIU,Two year,No,Mailed check,73.35,NaN,Female,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Yes,0,1
2775-SEFEE,Two year,Yes,Bank transfer (automatic),61.90,NaN,Male,0,No,Yes,DSL,Yes,Yes,No,Yes,No,No,Yes,0,1

**Пропуски связаны с дилиноой контракта в один день, значит можем заменить их на 0**

In [105]:
df['totalcharges'].fillna(0, inplace=True)

**Приведём столбец 'seniorsitezen' к категоральному виду, каким он и является, заменив '1', '0' на ''YES, 'NO'.**

In [106]:
df['seniorcitizen'] = np.where(df['seniorcitizen'] == 1, 'YES', 'NO')

**Проверка**

In [107]:
df

,type,paperlessbilling,paymentmethod,monthlycharges,totalcharges,gender,seniorcitizen,partner,dependents,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,multiplelines,outflow,contract_length
customerID,,,,,,,,,,,,,,,,,,,
7590-VHVEG,Month-to-month,Yes,Electronic check,29.85,29.85,Female,NO,Yes,No,DSL,No,Yes,No,No,No,No,NaN,0,32
5575-GNVDE,One year,No,Mailed check,56.95,1889.50,Male,NO,No,No,DSL,Yes,No,Yes,No,No,No,No,0,1037
3668-QPYBK,Month-to-month,Yes,Mailed check,53.85,108.15,Male,NO,No,No,DSL,Yes,Yes,No,No,No,No,No,1,62
7795-CFOCW,One year,No,Bank transfer (automatic),42.30,1840.75,Male,NO,No,No,DSL,Yes,No,Yes,Yes,No,No,NaN,0,1372
9237-HQITU,Month-to-month,Yes,Electronic check,70.70,151.65,Female,NO,No,No,Fiber optic,No,No,No,No,No,No,No,1,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6840-RESVB,One year,Yes,Mailed check,84.80,1990.50,Male,NO,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Yes,0,731
2234-XADUH,One year,Yes,Credit card (automatic),103.20,7362.90,Female,NO,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Yes,0,2192
4801-JZAZL,Month-to-month,Yes,Electronic check,29.60,346.45,Female,NO,Yes,Yes,DSL,Yes,No,No,No,No,No,NaN,0,338
8361-LTMKD,Month-to-month,Yes,Mailed check,74.40,306.60,Male,YES,Yes,No,Fiber optic,No,No,No,No,No,No,Yes,1,124
3186-AJIEK,Two year,Yes,Bank transfer (automatic),105.65,6844.50,Male,NO,No,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,No,0,2011

**Изучим уникальные значения категоральных прризнаков**

In [108]:
cat_features = np.array(df.select_dtypes(include=['object']).columns)
for z in cat_features:
    print(z + ':', df[z].unique())

type: ['Month-to-month' 'One year' 'Two year']
paperlessbilling: ['Yes' 'No']
paymentmethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
gender: ['Female' 'Male']
seniorcitizen: ['NO' 'YES']
partner: ['Yes' 'No']
dependents: ['No' 'Yes']
internetservice: ['DSL' 'Fiber optic' nan]
onlinesecurity: ['No' 'Yes' nan]
onlinebackup: ['Yes' 'No' nan]
deviceprotection: ['No' 'Yes' nan]
techsupport: ['No' 'Yes' nan]
streamingtv: ['No' 'Yes' nan]
streamingmovies: ['No' 'Yes' nan]
multiplelines: [nan 'No' 'Yes']

**Заполним пропуски 'None'**

In [109]:
df.fillna('None', inplace=True)
display(df.sample(7))
df.info()

,type,paperlessbilling,paymentmethod,monthlycharges,totalcharges,gender,seniorcitizen,partner,dependents,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,multiplelines,outflow,contract_length
customerID,,,,,,,,,,,,,,,,,,,
1320-GVNHT,Two year,Yes,Credit card (automatic),108.40,7767.25,Male,NO,Yes,Yes,Fiber optic,Yes,Yes,Yes,No,Yes,Yes,Yes,0,2192
5063-IUOKK,Two year,No,Mailed check,19.75,265.75,Male,NO,No,No,None,None,None,None,None,None,None,No,0,397
0727-BMPLR,One year,Yes,Electronic check,100.00,5509.30,Female,YES,No,No,Fiber optic,No,No,Yes,No,Yes,Yes,Yes,1,1676
3423-HHXAO,One year,Yes,Mailed check,19.50,272.00,Female,NO,Yes,Yes,None,None,None,None,None,None,None,No,0,428
1534-OULXE,One year,Yes,Bank transfer (automatic),49.70,2961.40,Female,NO,Yes,Yes,DSL,Yes,No,No,No,No,No,No,0,1858
0361-HJRDX,Two year,No,Credit card (automatic),64.35,4539.60,Female,NO,No,No,DSL,Yes,Yes,Yes,Yes,Yes,Yes,None,0,2072
0374-FIUCA,Two year,Yes,Credit card (automatic),20.40,1414.45,Male,NO,Yes,No,None,None,None,None,None,None,None,No,0,1980

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   type              7043 non-null   object
 1   paperlessbilling  7043 non-null   object
 2   paymentmethod     7043 non-null   object
 3   monthlycharges    7043 non-null   float64
 4   totalcharges      7043 non-null   float64
 5   gender            7043 non-null   object
 6   seniorcitizen     7043 non-null   object
 7   partner           7043 non-null   object
 8   dependents        7043 non-null   object
 9   internetservice   7043 non-null   object
 10  onlinesecurity    7043 non-null   object
 11  onlinebackup      7043 non-null   object
 12  deviceprotection  7043 non-null   object
 13  techsupport       7043 non-null   object
 14  streamingtv       7043 non-null   object
 15  streamingmovies   7043 non-null   object
 16  multiplelines     7043 non-null   object
 17  outflow           7043 non-null   int64
 18  contract_length   7043 non-null   int64
dtypes: float64(2), int64(2), object(15)
memory usage: 1.3+ MB

**Проверим на дубли**

In [110]:
df.duplicated().sum()

18

_Удалим дубли_

In [111]:
df = df.drop_duplicates().reset_index(drop=True)

In [112]:
df.duplicated().sum()

0

## Исследовательский анализ данных

**Осмотрим датасет**

In [113]:
report = sv.analyze([df, 'review'])

                                             |                                             | [  0%]   00:00 ->…

In [114]:
report.show_html('review_analysis.html')

Report review_analysis.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

__Для открытия результатов используйте jupiter ==> file\open...\review_analysis.html__

**Вывод**

**Имеем 7025 строк, 19 признаков - 16 категоральных(включая таргет), 3 числовых.**

_Равная ритмичность графиков наводит на мысль что датасет сгенерирован:)_

**Сравним признаки с целевым**

In [115]:
report = sv.analyze([df,  'Outflow'], target_feat='outflow')
report.show_html('outflow.html')

                                             |                                             | [  0%]   00:00 ->…

Report outflow.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

**Для открытия результатов используйте jupiter ==> file\open...\outflow.html**

**Выводы:**

* Уровень изменения расчитан относительно одного признака

* type – тип оплаты: ежемесячный, годовой двухлетний, отток клиентов максимален при помесячной оплате в четыре раза выше 
  чем при годовой и в десять чем при двухлетнем контракте
  
* paperlessbilling – безбумажное выставление счетов, стимулирует к уходу в два раза чаще, по сравнению с бумажным

* paymentmethod – способ оплаты, электронный чек в два раза повышает отток по сравнению с чеком по почте, бакновским             переводом(автоматическим), списанием с кредитной карты(автоматическим)

* monthlycharges – ежемесячные траты на услуги, показывают очень слабую корреляцию при минимальном значении зависимости в точке   60

* totalcharges – всего потрачено денег на услуги показывают очень слабую корреляцию при тенденции снижения при увеличении суммы 
  расходов
  
* gender - пол, выявлен паритет

* senior Citizen – наличие пенсионного статуса по возрасту, пенсионеры склонны в два раза чаще отказываться от услуг

* partner – наличие супруга(и)  влияет слегка положительно и снижает отток на по этому признаку на треть, при очень слабой       корреляции

* dependents – наличие иждивенцев, улучшает отток(снижает) в два раза

* internetservise - наличие  оптики увеличивает отток в два раза по сравнению с DSL

* onlinesecurity - наличие сервиса снижает отток почти  втри раза

* onlinebackup - резеврное копирование онлайн снижает отток в два раза

* deviceprotection - защита устройства удучшает отток на 42 %

* techsupport - техническая поддержка почти в три раза уменьшает отток

* streamingtv - стриминговое тв не влияет на отток

* streamingmovies - стриминговый кинотеатр не влияет на отток

* multipleLines – наличие возможности ведения параллельных линий во время звонка не влияет на отток

* contract_length - длина контракта максимальное количество расторжений в первые дни и затем снижается

**Изучим численные признаки**

In [116]:
numerical = ['monthlycharges', 'totalcharges', 'contract_length']

In [117]:
df[numerical].corr()

                 monthlycharges  totalcharges  contract_length
monthlycharges         1.000000      0.650703         0.245416
totalcharges           0.650703      1.000000         0.825631
contract_length        0.245416      0.825631         1.000000

__Признак totalcharges сильно коррелирует с признаками contract_length и monthlycharges, удалим его , чтобы избежать мультиколлинеарности.__

**Дополнительные сервисы оказывают влияние на отток,т.к. они в отдельности каждый уменьшают отток, то чем их больше тем меньше отток, создадим признак показывающий количество сервисов у клиента, заменив им все дополнительные сервисы удалив их. Также удалим gendre как неинформативный, и сбросим индексы**

In [118]:
additional_services = df.iloc[:, 10:16].columns

def services(row):
    n=0
    for i in additional_services:
        if row[i]=='Yes':
            n+=1
        if row[i]=='None':
            n=-1
    return n

df['services'] = df.apply(services, axis=1)

In [119]:
df.reset_index(drop=True, inplace=True)
df.drop(list(additional_services) + ['gender', 'totalcharges'], axis=1, inplace=True)

In [120]:
df

,type,paperlessbilling,paymentmethod,monthlycharges,seniorcitizen,partner,dependents,internetservice,multiplelines,outflow,contract_length,services
0,Month-to-month,Yes,Electronic check,29.85,NO,Yes,No,DSL,None,0,32,1
1,One year,No,Mailed check,56.95,NO,No,No,DSL,No,0,1037,2
2,Month-to-month,Yes,Mailed check,53.85,NO,No,No,DSL,No,1,62,2
3,One year,No,Bank transfer (automatic),42.30,NO,No,No,DSL,None,0,1372,3
4,Month-to-month,Yes,Electronic check,70.70,NO,No,No,Fiber optic,No,1,62,0
...,...,...,...,...,...,...,...,...,...,...,...,...
7020,One year,Yes,Mailed check,84.80,NO,Yes,Yes,DSL,Yes,0,731,5
7021,One year,Yes,Credit card (automatic),103.20,NO,Yes,Yes,Fiber optic,Yes,0,2192,4
7022,Month-to-month,Yes,Electronic check,29.60,NO,Yes,Yes,DSL,None,0,338,1
7023,Month-to-month,Yes,Mailed check,74.40,YES,Yes,No,Fiber optic,Yes,1,124,0
7024,Two year,Yes,Bank transfer (automatic),105.65,NO,No,No,Fiber optic,No,0,2011,5

**Исследуем баланс классов целевого признака.**

In [121]:
round(df['outflow'].value_counts() / len(df), 2)

0    0.74
1    0.26
Name: outflow, dtype: float64

**Имеем дисбаланс объектов, нулевого класса почти в три раза больше , чем объектов единичного**

### Вывод

**Составим портрет самого надежного и лояльного клиента**

_Это мужчина или женщина с двухлетним контрактом, предпочитающие бумажные счета, но оплачиваемые кредитной картой с автосписанием:), с месячной абонентской платой 60, в браке, с детьми, не пенсионного возраста,  использующие DSL, антивирус, резервное копирование, техническую поддержку и другие сервисы._

## Построение модели

### CatBoost

**Создадим списки признаков**

In [122]:
X = ['monthlycharges', 'contract_length', 'type', 'paperlessbilling', 'paymentmethod', 'seniorcitizen',
 'partner', 'dependents', 'internetservice', 'services',
'multiplelines']

cat_features = ['type', 'paperlessbilling', 'paymentmethod', 'seniorcitizen',
 'partner', 'dependents', 'internetservice', 'multiplelines'] 

y = ['outflow']

**Создадим обучающую и тестовую выборку**

In [123]:
train, test = train_test_split(df,train_size=0.8,random_state=77)

**Создание POOL**

In [124]:
train_data = Pool(data=train[X],
                  label=train[y],
                  cat_features=cat_features
                 )

In [125]:
test_data = Pool(data=test[X],
                  label=test[y],
                  cat_features=cat_features
                 )

**Кросс валидация**

In [169]:
params = {'cat_features': cat_features,
          'eval_metric': 'AUC',
          'loss_function': 'Logloss',
          'learning_rate': 0.11,
          'random_seed': 77,
          'verbose':100,
          'scale_pos_weight': 74/26}

In [178]:
cv_data = cv(
    params = params,
    pool = train_data,
    fold_count=5,
    shuffle=True,
    partition_random_seed=0,
    plot=True,
    stratified=True,
    verbose=False,
    early_stopping_rounds=200
)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

**Найдём лучшую итерацию**

In [171]:
cv_data.head()

,iterations,test-AUC-mean,test-AUC-std,test-Logloss-mean,test-Logloss-std,train-Logloss-mean,train-Logloss-std
0,0,0.809179,0.009132,0.650075,0.003352,0.649431,0.004748
1,1,0.826349,0.011508,0.619394,0.003365,0.617987,0.004241
2,2,0.827459,0.011791,0.601689,0.005186,0.599791,0.008831
3,3,0.830644,0.013401,0.581178,0.004798,0.578142,0.005117
4,4,0.833419,0.012045,0.565596,0.004958,0.562210,0.003502

In [172]:
cv_data[cv_data['test-AUC-mean'] == cv_data['test-AUC-mean'].max()]

,iterations,test-AUC-mean,test-AUC-std,test-Logloss-mean,test-Logloss-std,train-Logloss-mean,train-Logloss-std
820,820,0.913715,0.015215,0.39365,0.045901,0.140905,0.005712

In [173]:
n_iters = cv_data[cv_data['test-AUC-mean'] == cv_data['test-AUC-mean'].max()]['iterations'].values[0]

In [179]:
n_iters

820

**Обучение на всех данных**

In [186]:
params = {'cat_features': cat_features,
          'eval_metric': 'AUC',
          'loss_function': 'Logloss',
          'learning_rate': 0.11,
          'random_seed': 77,
          'verbose':100,
          'scale_pos_weight': 74/26,
          'iterations': 820}

In [187]:
model = CatBoostClassifier(**params)

In [188]:
model.fit(train_data)

0:	total: 21.7ms	remaining: 17.7s
100:	total: 2.68s	remaining: 19.1s
200:	total: 5.61s	remaining: 17.3s
300:	total: 8.75s	remaining: 15.1s
400:	total: 11.7s	remaining: 12.2s
500:	total: 14.6s	remaining: 9.29s
600:	total: 17.6s	remaining: 6.41s
700:	total: 20.6s	remaining: 3.5s
800:	total: 23.7s	remaining: 562ms
819:	total: 24.3s	remaining: 0us

**Предсказание на тесте**

In [189]:
test['y_pred'] = model.predict_proba(test_data)[:,1]

C:\Users\bogda\AppData\Local\Temp/ipykernel_1304/2601031922.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['y_pred'] = model.predict_proba(test_data)[:,1]

In [190]:
roc_auc_score(test['outflow'],test['y_pred'])

0.9314265015806112

**Необходимая точность достигнута, дальнейшее моделирование нецелесообразно**

## Отчёт